### ISSUE TITLE
Unregistered ConfiguredFeatures found in Vanilla Enhanced

### ISSUE THREAD

**Issue by TelepathicGrunt** [CamoMano/Vanilla-Enhanced#18]
Hello! I was testing my World Blender and Blame mod with other worldgen mods to see what is compatible with my mods. What Blame found was that Vanilla Enhanced has some unregistered ConfiguredFeatures. This can be an issue for mod compatibility as under certain conditions, unregistered ConfiguredFeatures can basically prevent other mod's registered ConfiguredFeatures from spawning if in the same generation stage.

By that I mean, if mod A adds an unregistered CF to the ore generation stage and the biome's codec reaches it first, it will choke and basically nuke mob B's registered CFs afterwards. Here's a case where BetterCaves forgot to register their CF and caused several CFs from Oh The Biomes You'll Go to stop spawning in the world: yungnickyoung/YUNGs-Better-Caves#75

Here's a more detailed explanation of why this happens in the biome's codec:
![image](https://user-images.githubusercontent.com/40846040/95884310-f048ab00-0d49-11eb-9d84-569f528e4daf.png)

Specifically, when you call .configure on a Feature, you create a ConfiguredFeature. This is what should be registered to the WorldGenRegisties at mod init.

Anyway here's an example from my mod RepurposedStructures of me registering all my ConfiguredFeatures.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/584433a0745338802c84e9f498dc063c1f5505f8/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSConfiguredFeatures.java#L184-L185

I hope this helps!

From the latets.log with Blame on:
****************** Blame Report 2.2.3b ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

 Possible mods responsible for unregistered stuff:

vanillaenhanced:amethyst_ore
vanillaenhanced:dark_granite
vanillaenhanced:marble
vanillaenhanced:redwood_leaves
vanillaenhanced:redwood_log
vanillaenhanced:ruby_ore
vanillaenhanced:sapphire_ore

**Comment by CamoMano** [comment]
Thank you for bringing this to my attention. I'll have to look into this further.

**Comment by RDKRACZ** [comment]
Oh I wanted to open issue to paste blame report but You were first.

**Comment by CamoMano** [comment]
Fixed in #20
