### ISSUE TITLE
Some tools aren't in the fabric namespace?

### ISSUE THREAD

**Issue by RDKRACZ** [CamoMano/Vanilla-Enhanced#19]
I was checking if your mod support [Tiered](https://github.com/Draylar/tiered/) mod and seems like Sapphire and Ruby tools aren't compatible.
https://www.curseforge.com/minecraft/mc-mods/tiered
"Mods need to add their tools to the respective tags inside the fabric namespace (fabric:pickaxes, fabric:chestplates, fabric:shovels, etc.)"

**Comment by CamoMano** [comment]
Fixed in #20
