### ISSUE TITLE
Redwood sapling cannot be potted

### ISSUE THREAD

**Issue by CatastropheBlack** [CamoMano/Vanilla-Enhanced#22]
**Describe the bug**
Redwood sapling cannot be placed in vanilla pot.

**Steps To Reproduce**
Right click on vanilla pot with redwood sapling.  

**Expected behavior**
Sapling will be placed in pot.

**Environment:**
 - VanillaEnhanced 1.5
 - Minecraft 1.16.5
 - Fabric API 0.11.3

**Comment by CamoMano** [comment]
Fix will be available with the next update.
