### ISSUE TITLE
Redwood leaves don't use color providers.

### ISSUE THREAD

**Issue by LambdAurora** [CamoMano/Vanilla-Enhanced#28]
**Describe the bug**
Redwood leaves don't use color providers for the block form nor the item form.

**Expected behavior**
Redwood leaves should use color providers to increase compatibility with minimap mods and other mods relying on the presence of color providers for leaves.

**Additional context**
This is mostly a compatibility issue, minimap mods will often use the `MapColor` or a `BlockColorProvider` if present. If no `BlockColorProvider` is present it might appear gray instead.

**Comment by LambdAurora** [comment]
The version of VanillaEnhanced used is 1.6.1, the minimap mod concerned is [LambdaMap](https://github.com/LambdAurora/LambdaMap). It also affects the content mod [Aurora's Decorations](https://github.com/LambdAurora/AurorasDecorations) as it can't deduce the coloring of the leaf part of the stump block.

**Comment by CamoMano** [comment]
Are you able to provide me with builds of these mods so I can do some testing?

**Comment by LambdAurora** [comment]
I won't be able to provide a build of LambdaMap as I haven't updated it yet, but it's similar to [Blockus#71](https://github.com/Brandcraf06/Blockus/pull/71).

For Aurora's Decorations the JAR file can be fetched from the GitHub actions: https://github.com/LambdAurora/AurorasDecorations/suites/2952400489/artifacts/66426089

**Comment by CamoMano** [comment]
Thank you. I'll likely release a patch for this later.
