### ISSUE TITLE
Redwood Slabs don't act like slabs

### ISSUE THREAD

**Issue by Tsolval** [CamoMano/Vanilla-Enhanced#34]
**Describe the bug**
Redwood slabs take longer to mine than other wooden slabs and do not mine faster with an axe than with an empty hand.  Also, Redwood slabs cannot be used in crafting recipes that take slabs, such as a lectern.

**Steps To Reproduce**
1. Start up a world running Vanilla Enhanced and go to a redwood forest.
2. Cut down a redwood tree and a spruce tree and use them to make 6 redwood slabs and 6 spruce slabs.
3. Place a redwood slab and a spruce slab, they should mine at the same speed, but they do not. 
4. Attempt to make a lectern in a crafting table.  The recipe works with spruce slabs, but does not work with redwood slabs

**Expected behavior**
The redwood slab should behave as other wooden slabs do.

**Screenshots**
Recipe Screenshots:
[Lectern with Redwood Slabs](https://i.imgur.com/ykMVTTX.png)
[Lectern with Spruce Slabs](https://i.imgur.com/tt9HVsX.png)

**Environment:**
 - VanillaEnhanced Version: 1.7.0
 - Minecraft Version: 1.17
 - Fabric Loader Version: 0.11.6
 - Fabric API Version: 0.36.0

**Comment by CamoMano** [comment]
Thank you for reporting. Will be fixed in the next update.
